name: Publish Package to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Deno - Latest
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Setup Node.js - 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build for npm
        run: deno run -A ./scripts/build.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd npm
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
