name: Pull request testing

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/pull-request-testing.yml"
      - "**/*.ts"

jobs:
  dependencies:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Deno - Latest
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run tests
        run: deno test
        env:
          CI: true
